```{r librerias y configuraciones}
library(magrittr)
library(dplyr)
library(readr)
library(skimr)
library(ggplot2)
library(conflicted)
conflicts_prefer(dplyr::filter, .quiet = TRUE)
options(dplyr.summarise.inform = FALSE)
```

```{r 1}
#Cargue la base de datos y almacene su contenido en un objeto llamado “datos”.
datos <- read.delim("C:/Universidad/ANALEC/Laboratorio-ANALEC/2023_05_CCG_Votacion.txt", header = TRUE, sep = "|")
saveRDS(datos, file = "ccg.rds")
```

```{r 2}
#Realice una inspección de los datos y proporcione el número de observaciones y variables en el conjunto de datos.
skim(datos)
```

De acuerdo con los datos, hay 1.058.415 observaciones en 17 variables.

```{r 3}
#Transforme la variable “Nro.voto” a numérica.
datos$Nro.voto <- as.numeric(datos$Nro.voto)
##
class(datos$Nro.voto)
```

```{r 4}
#Otorgue nuevos nombres a las siguientes variables
colnames(datos)[13:17] <-
  c("Nombres", "Apellido1", "Apellido2", "Cargo", "Votos")
```

```{r 5}
#Obtenga una lista (única) de las distintas regiones presentes en la base de datos.
unique(datos$Region)
```

```{r 6}
#Elimine las filas que contienen totales de votos nulos o en blanco al final de cada mesa para garantizar una representación precisa de los datos de la elección. Luego, proporcione el número actualizado de observaciones en el conjunto de datos
datos_vv <- datos %>% 
  filter(!is.na(Nro.voto))
##
colnames(datos_vv)[13:17] <-
  c("Nombres", "Apellido1", "Apellido2", "Cargo", "Votos")
##
skim(datos_vv)
```

De acuerdo con los datos actualizados, hay 981.085 observaciones en 17 variables.

```{r 7}
#Calcule el número total de votos emitidos en la elección.
sum(datos$Votos)
##
sum(datos_vv$Votos)
```

De acuerdo con los datos, fueron emitidos 12.506.673 votos; de los cuales 9.813.212 fueron votos válidamente emitidos.

```{r 8}
#Calcule y compare el número de votos obtenidos por cada partido en la elección.
vxp <- datos_vv %>% 
  group_by(Partido) %>% 
  summarise(Votos = sum(Votos))
```

```{r 9}
#Identifique el partido con la mayor cantidad de votos y el partido con la menor cantidad de votos en la elección
vxp %>% 
  slice(which.max(Votos),
        which.min(Votos))
```

```{r 10 !}
#Cree un gráfico que muestre la cantidad de votos entre los partidos en la elección
ggplot(vxp, aes(x = Partido,
                y = Votos)) +
  labs(title = "Gráfico de Barras", 
       x = "Partido", 
       y = "Votos") + 
  geom_histogram(stat = "identity", fill = "blue") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```
  
```{r 11}
#Calcule y compare el número total de votos emitidos por cada región en la elección.
vxr <- datos %>% 
  group_by(Region) %>% 
  summarise(Votos = sum(Votos))
```

```{r 12}
#Utilizando la base de datos inicial, obten la cantidad de votos nulos o en blancos por región. 
#Calcula y compara el porcentaje de votos nulos o en blanco respecto a los validamente emitidos.
##como dice votos nulos *o* blancos no los puedo sumar
vxr_bn <- datos %>% 
  filter(is.na(Nro.voto)) %>% 
  group_by(Nombres, Region) %>% 
##group_by() se rompe y reclama al usar dos variables
##no tengo la menor idea de por que
  summarise(Votos = sum(Votos)) %>% 
  pivot_wider(names_from = Nombres, values_from = Votos) %>%
##no me acuerdo si vimos pivot_wider() en la ayudantía
  mutate(votos = vxr$Votos,
         pb = round(`VOTOS EN BLANCO` / votos * 100, digits = 1),
         pn = round(`VOTOS NULOS` / votos * 100, digits = 1),
         pv = round(((votos - (`VOTOS NULOS`+`VOTOS EN BLANCO`)) / votos) * 100, digits = 1))
##
vxr_bn <- vxr_bn[, c(1,2,5,3,6,4,7)] %>% 
  `colnames<-`(c("Region", 
                 "Votos en blanco",
                 "Porcentaje de votos en blanco",
                 "Votos nulos", 
                 "Porcentaje de votos nulos",
                 "Votos válidamente emitidos",
                 "Porcentaje de votos válidamente emitidos"))
#reordenar y renombrar headers
```

